SmartShare/SmartShare/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartShare.Models;
using System.Web.Security;
//using System.Web.UI.WebControls;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Http;
using System.ComponentModel;
using System.Web.Hosting;
using System.Net.Http.Headers;
using System.Net;

namespace SmartShare.Controllers
{
    public class HomeController : Controller
    {
        private AdvertisementsContext db = new AdvertisementsContext();

        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View(db.AdvertisementsDb.ToList());
        }

        //public FileContentResult getImg(int id)
        //{
        //    Advertisements advertisements = db.AdvertisementsDb.Find(id);
        //    byte[] byteArray = advertisements.AdvertisementImage;
        //    if (byteArray != null)
        //    {
        //        return new FileContentResult(byteArray, "image/jpeg");
        //    }
        //    else
        //    {
        //        return null;
        //    }
        //}

        public Image getImgae(int id)
        {
            Advertisements advertisements = db.AdvertisementsDb.Find(id);
            byte[] byteArray = advertisements.AdvertisementImage;

            if (byteArray != null)
            {
                MemoryStream memoryStream = new MemoryStream(byteArray);
                return Image.FromStream(memoryStream);
            }
            else
            {
                return null;
            }
        }

        //public HttpResponseMessage getImage(int id)
        //{
        //    HttpResponseMessage response = new HttpResponseMessage();

        //    Advertisements advertisements = db.AdvertisementsDb.Find(id);
        //    TypeConverter typeConverter = TypeDescriptor.GetConverter(typeof(Bitmap));
        //    Bitmap bmp = (Bitmap)typeConverter.ConvertFrom(advertisements.AdvertisementImage);

        //    var Fs = new FileStream(HostingEnvironment.MapPath("~/Images") + @"\I" + id.ToString() + ".png", FileMode.Create);
        //    bmp.Save(Fs, ImageFormat.Png);
        //    bmp.Dispose();

        //    Image img = Image.FromStream(Fs);
        //    Fs.Close();
        //    Fs.Dispose();

        //    MemoryStream ms = new MemoryStream();
        //    img.Save(ms, ImageFormat.Png);

        //    response.Content = new ByteArrayContent(ms.ToArray());
        //    ms.Close();
        //    ms.Dispose();

        //    response.Content.Headers.ContentType = new MediaTypeHeaderValue("image/png");
        //    response.StatusCode = HttpStatusCode.OK;

        //    return response;
        //}

        //
        // GET: /Home/Details/5

        public ActionResult Details(int id = 0)
        {
            Advertisements advertisements = db.AdvertisementsDb.Find(id);
            if (advertisements == null)
            {
                return HttpNotFound();
            }
            return View(advertisements);
        }

        //
        // GET: /Home/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Home/Create

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Advertisements advertisements, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                MembershipUser user = Membership.GetUser(User.Identity.Name);
                advertisements.UserId = (Int32)user.ProviderUserKey;
                advertisements.CreatedOn = DateTime.Now;

                if (file != null)
                {
                    MemoryStream target = new MemoryStream();
                    file.InputStream.CopyTo(target);
                    byte[] data = target.ToArray();

                    advertisements.AdvertisementImage = data;
                }



                db.AdvertisementsDb.Add(advertisements);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(advertisements);
        }

        //
        // GET: /Home/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Advertisements advertisements = db.AdvertisementsDb.Find(id);
            if ((Int32)Membership.GetUser(User.Identity.Name).ProviderUserKey == advertisements.UserId)
            {
                if (advertisements == null)
                {
                    return HttpNotFound();
                }
                return View(advertisements);
            }

            return RedirectToAction("Index");
        }

        //
        // POST: /Home/Edit/5

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Advertisements advertisements)
        {
            if (ModelState.IsValid)
            {
                db.Entry(advertisements).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(advertisements);
        }

        //
        // GET: /Home/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Advertisements advertisements = db.AdvertisementsDb.Find(id);
            if ((Int32)Membership.GetUser(User.Identity.Name).ProviderUserKey == advertisements.UserId)
            {
                if (advertisements == null)
                {
                    return HttpNotFound();
                }
                return View(advertisements);
            }

            return RedirectToAction("Index");
        }

        //
        // POST: /Home/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advertisements advertisements = db.AdvertisementsDb.Find(id);
            db.AdvertisementsDb.Remove(advertisements);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SmartShare/SmartShare/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartShare.Models;

namespace SmartShare.Controllers
{
    public class NotificationController : Controller
    {
        private NotificationContext db = new NotificationContext();

        //
        // GET: /Notification/

        public ActionResult Index()
        {
            return View(db.NotificationDb.ToList());
        }

        //
        // GET: /Notification/

        public ActionResult Inbox()
        {
            return View(db.NotificationDb.ToList());
        }

        public ActionResult Outbox()
        {
            return View(db.NotificationDb.ToList());
        }

        //
        // GET: /Notification/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            Notifications notifications = db.NotificationDb.Find(id);
            if (notifications == null)
            {
                return HttpNotFound();
            }
            return View(notifications);
        }

        //
        // GET: /Notification/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            ViewBag.AdId = "" + id;
            return View();
        }

        //
        // POST: /Notification/Create

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Notifications notifications)
        {
            if (ModelState.IsValid)
            {
                db.NotificationDb.Add(notifications);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(notifications);
        }

        //
        // GET: /Notification/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Notifications notifications = db.NotificationDb.Find(id);
            if (notifications == null)
            {
                return HttpNotFound();
            }
            return View(notifications);
        }

        //
        // POST: /Notification/Edit/5

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Notifications notifications)
        {
            if (ModelState.IsValid)
            {
                db.Entry(notifications).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(notifications);
        }

        //
        // GET: /Notification/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Notifications notifications = db.NotificationDb.Find(id);
            if (notifications == null)
            {
                return HttpNotFound();
            }
            return View(notifications);
        }

        //
        // POST: /Notification/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Notifications notifications = db.NotificationDb.Find(id);
            db.NotificationDb.Remove(notifications);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SmartShare/SmartShare/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h1>@ViewBag.Title.</h1>
<h2>@ViewBag.Message</h2>

<article>
    <p>
        The objective of this project is to develop a small scale project for "Windows Azure Platform" and learn some features of ASP .NET MVC4 also. Basic functionalities of the project are following:
    </p>
    <p>
        <ul>
            <li>Public users can see list of items in the home page which are going to be sold or bought.</li>
            <li>Public users can search item by categories.</li>
            <li>Users (registered users) can reply/comment to a post or send message to the post creator.</li>
            <li>Users (registered users) can submit posts regarding item selling, renting out house or asking help for something.</li>
        </ul>
    </p>
</article>

SmartShare/SmartShare/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h1>@ViewBag.Title.</h1>
<h2>@ViewBag.Message</h2>

<ol>
    <li>
        <p>
        Md. Mesbahul Islam <br />
        Deapartment of Computer Science (Networking and Services) <br />
        University of Helsinki <br />
        E-mail: mdislam [at] cs [dot] helsinki [dot] fi
        </p>
    </li>

    <li>
        <p>
        Adnan Mohammad Shoeb Shatil <br />
        Deapartment of Computer Science (Algorithms and Data Mining) <br />
        University of Helsinki <br />
        E-mail: andan [dot] shatil [at] cs [dot] helsinki [dot] fi
        </p>
    </li>
    
    <li>
        <p>
        A. M. Ahsan Feroz <br />
        Geoinformatics, Department of Real Estate, Planning and Geoinformatics <br />
        Aalto University, School of Engineering <br />
        E-mail: abdullah.feroz [at] aalto [dot] fi <br />
        </p>
    </li>
</ol>

SmartShare/SmartShare/Views/Home/Create.cshtml
@model SmartShare.Models.Advertisements

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Home", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Advertisements</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdvertisementTitle)
            @Html.ValidationMessageFor(model => model.AdvertisementTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementDesc)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.AdvertisementDesc)
            @Html.ValidationMessageFor(model => model.AdvertisementDesc)
        </div>

        @*<p>
            <input type="hidden" id="imageFilePath" value="" />
        </p>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementImage)
        </div>
        <div class="editor-field">
            <input type='file' name='file' id='file' />
        </div>

        
        

        @*<div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>*@

        @*<div class="editor-label">
            @Html.LabelFor(model => model.CreatedOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedOn)
            @Html.ValidationMessageFor(model => model.CreatedOn)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryType)
            @Html.ValidationMessageFor(model => model.CategoryType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdvertisementType)
            @Html.ValidationMessageFor(model => model.AdvertisementType)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SmartShare/SmartShare/Views/Home/Delete.cshtml
@model SmartShare.Models.Advertisements

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Advertisements</legend>

    <div>
        <div style="width: 85%; margin: 0 auto;float: left; padding: 5px">
            <h3>@Model.AdvertisementTitle - [I have used hard coded styles here]</h3>
        </div>
        <div style="width: 50%; margin: 0 auto; float: left; padding: 10px">
            <p><i>Created by <b>@Model.UserId</b> [need to replace the userid by username] on @Model.CreatedOn.ToShortDateString()</i></p>

            <p>
                Description: @Model.AdvertisementDesc
                <br />
                Price: @Model.Price euro
                <br />
                
            </p>
        </div>
    </div>
</fieldset>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p id="linkBtns">
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SmartShare/SmartShare/Views/Home/Details.cshtml
@model SmartShare.Models.Advertisements

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Advertisements</legend>

    <div>
        <div style="width: 85%; margin: 0 auto;float: left; padding: 5px">
            <h3>@Model.AdvertisementTitle - [I have used hard coded styles here]</h3>
        </div>
        <div style="width: 50%; margin: 0 auto; float: left; padding: 10px">
            <p><i>Created by <b>@Model.UserId</b> [need to replace the userid by username] on @Model.CreatedOn.ToShortDateString() @Model.CreatedOn.ToShortTimeString()</i></p>

            <p>
                Description: @Model.AdvertisementDesc
                <br />
                Type: @Model.AdvertisementType
                <br />
                Category: @Model.CategoryType
                <br />
                Price: @Model.Price euro
                <br />
            </p>
        </div>
        <div style="width: 30%; margin: 0 auto; float: left; padding: 5px">
            <img src="@Url.Action("getImg", "Home", new { modelItem = Model.AdvertisementID })" alt="Item Image" />
        </div>
    </div>
</fieldset>
<p id="linkBtns">
    @Html.ActionLink("Back to List", "Index")
</p>
<p id="linkBtns">
    @Html.ActionLink("Reply", "Create", "Notification", new { id=Model.AdvertisementID }, null)
</p>

SmartShare/SmartShare/Views/Home/Edit.cshtml
@model SmartShare.Models.Advertisements

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Advertisements</legend>

        @Html.HiddenFor(model => model.AdvertisementID)

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdvertisementTitle)
            @Html.ValidationMessageFor(model => model.AdvertisementTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementDesc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdvertisementDesc)
            @Html.ValidationMessageFor(model => model.AdvertisementDesc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedOn)
            @Html.ValidationMessageFor(model => model.CreatedOn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryType)
            @Html.ValidationMessageFor(model => model.CategoryType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AdvertisementType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdvertisementType)
            @Html.ValidationMessageFor(model => model.AdvertisementType)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div id="linkBtns">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SmartShare/SmartShare/Views/Home/Index.cshtml
@model IEnumerable<SmartShare.Models.Advertisements>

@{
    ViewBag.Title = "Index";
}

<h2>Advertisements List</h2>

<p id="advertisement">
    @Html.ActionLink("Add New Advertisement", "Create")
</p>

<hr style="border:double"/>

@foreach (var item in Model)
{
    <article>
        <div>
            <h3>@Html.DisplayFor(modelItem => item.AdvertisementTitle)</h3>
            <p><i>Created by <b>@item.UserId</b> [need to replace the userid by username] on @item.CreatedOn.ToShortDateString() @item.CreatedOn.ToShortTimeString()</i></p>
            <p>@item.AdvertisementDesc</p>
        </div>

        <div id="linkBtns">@Html.ActionLink("Details", "Details", new { id = item.AdvertisementID })</div>
        <hr />
    </article>
}